### ISSUE TITLE
h5py 3.0 breaks write on latest 'tag' release

### ISSUE THREAD

**Issue by mzakharocsc** [frejanordsiek/hdf5storage#101]
Hello,

package on pypi is old, and does not work with latest h5py release 3.0.  master works fine. Can someone please release a new tag? (and push it to pypi please)?

**Comment by bnavigator** [comment]
Bump?

**Comment by Bengt** [comment]
O-M-G. It took me way too long to figure this one out.

For future reference, this was my error:

```
mosaik_hdf5_storage/hdf5_writer/writer.py:78: in write
    hdf5storage.write(
.tox/py38/lib/python3.8/site-packages/hdf5storage/__init__.py:1397: in write
    writes(mdict={path: data},  filename=filename,
.tox/py38/lib/python3.8/site-packages/hdf5storage/__init__.py:1318: in writes
    lowlevel.write_data(f, grp, targetname, data,
.tox/py38/lib/python3.8/site-packages/hdf5storage/lowlevel.py:114: in write_data
    m.write(f, grp, name, data, type_string, options)
.tox/py38/lib/python3.8/site-packages/hdf5storage/Marshallers.py:1583: in write
    self.write_metadata(f, grp, name, data, type_string, options)
.tox/py38/lib/python3.8/site-packages/hdf5storage/Marshallers.py:1608: in write_metadata
    TypeMarshaller.write_metadata(self, f, grp, name, data,
.tox/py38/lib/python3.8/site-packages/hdf5storage/Marshallers.py:409: in write_metadata
    set_attribute_string(grp[name], 'Python.Type', type_string)
.tox/py38/lib/python3.8/site-packages/hdf5storage/utilities.py:784: in set_attribute_string
    set_attribute(target, name, np.bytes_(value))
.tox/py38/lib/python3.8/site-packages/hdf5storage/utilities.py:759: in set_attribute
    target.attrs.create(name, value)
.tox/py38/lib/python3.8/site-packages/h5py/_hl/attrs.py:197: in create
    attr = h5a.create(self._id, self._e(tempname), htype, space)
h5py/_objects.pyx:54: in h5py._objects.with_phil.wrapper
    ???
h5py/_objects.pyx:55: in h5py._objects.with_phil.wrapper
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

>   ???
E   RuntimeError: Unable to create attribute (no write intent on file)

h5py/h5a.pyx:50: RuntimeError
```

Line for a requirements.txt:

    -e git://github.com/frejanordsiek/hdf5storage.git@09dfc5fb3a6a3f9c32c2479a896c7f14d3c8d830#egg=hdf5storage

Install command for pip:

    python -m pip install -e git://github.com/frejanordsiek/hdf5storage.git@09dfc5fb3a6a3f9c32c2479a896c7f14d3c8d830#egg=hdf5storage

**Comment by frejanordsiek** [comment]
See Issue #102 . I have an issue I need to sort out with h5py first (a key Attribute can no longer be read by h5py anymore, so I need a work around) and then this issu will be fixed. Then a new release for the ``0.1.x`` branch will be made (0.1.16) and uploaded to PyPI. As for the ``main`` branch, no release on that branch is yet scheduled. There is still a lot of work to do on that branch before its first release, namely I need to essentially finish the package so that it only needs maintainence in the future rather than feature additions.

**Comment by frejanordsiek** [comment]
The problems are fixed in both the 0.1.x and main branches.

I will be uploading version 0.1.16 to PyPI shortly.

**Comment by Bengt** [comment]
Awesome. Thanks!

For reference, 0.1.16 has just been released:

https://pypi.org/project/hdf5storage/0.1.16/

**Comment by Bengt** [comment]
Now I can move about a dozen projects away from installing HDF5Storage from GitHub to PyPI. That feels much safer.

**Comment by Bengt** [comment]
Version 0.1.16 works fine for all use cases in my test suites. Great!
