### ISSUE TITLE
Matlab cannot load the .mat file 

### ISSUE THREAD

**Issue by xiaoluomi** [frejanordsiek/hdf5storage#116]
Hi , I had some problems when using hdf5storage.savemat(). I use Python to save the data into a .mat file through the hdf5storage.savemat() function, but when I open my MATLAB, my matlab cannot load these saved data files(error:Cannot read mat file, not binary mat file. Try load - ASCII to be in text form Read.). Is there any way to solve this situation?, Sincerely ask you for help.

**Comment by frejanordsiek** [comment]
Sorry I missed this earlier. Were you able to figure it out. If now, reducing the file down to just the smallest that causes the problem may give an insight into the problem.
