### ISSUE TITLE
loadmat represents empty MATLAB struct as a 1x1 array

### ISSUE THREAD

**Issue by randallpittman** [frejanordsiek/hdf5storage#121]
Creation of `tmp.mat` with a scalar, an empty struct, and an empty cell array:

```matlab
S = struct('A', 123, 'B', struct(), 'C', {{}});
save('tmp.mat', '-struct', 'S', '-v7.3');
```

Loading with hdf5storage 0.1.18:
```python
import hdf5storage
mat = hdf5storage.loadmat("tmp.mat")
mat
````
Output:
```
{'A': array([[123.]]),
 'B': array([[0]], dtype=object),
 'C': array([], shape=(0, 0), dtype=object)}
```

Looking back at `S.B` in MATLAB I get that `mat["B"]` has 1x1 dimensions because in MATLAB `S.B` is a 1x1 empty `struct`. However at first glance I see that it has value of `0` and I think it's some sort of scalar numeric. I don't know if there's any better way to represent an empty struct, but I figured this should at least be documented.

**Comment by randallpittman** [comment]
I guess the `stucts_as_dicts` option (ref #115) would alleviate this.

**Comment by frejanordsiek** [comment]
Looking at the output, `B` is an object array. For object arrays, `0` is the same as `NULL`. A null pointer.

So, I think this is working as it should.
