### ISSUE TITLE
Confusion about versions

### ISSUE THREAD

**Issue by szapp** [frejanordsiek/hdf5storage#128]
I am a bit confused about the version(s) of this package.

An installation via PIP gives ***version 0.1.19***. The README of this repo distinguishes between versions 0.1 and 0.2. However, there is no release, git tag, or any mention anywhere else for a ***version 0.2***. Moreover, there is a milestone in the repo for another version: ***version 1.0***. The branch 0.1.x of this repo has diverged from the main branch in 2015 and doesn't seem to have any intersection with the main branch since then while both of them continuously received commits. That has me curious, because I want to avoid creating files that will become invalid in the future due to possible backward-incompatibility.

 - Is there any documentation of the versioning process or roadmap available?

 - Am I at risk of future-incompatibilities if I create MAT-files (with version 0.1.19) that are intended for longer-term storage?

 - Is there a way to use version 0.2?

I am interested in the version 0.2 in particular, since it seems to support saving slices and ranges in matlab-compatible form.

**Comment by szapp** [comment]
No longer of interest

**Comment by frejanordsiek** [comment]
Going to put an answer here for anyone else who is reading this.

0.2 is the placeholder version of the development branch, that when finished will be incremented to 1.0 and then releases.

As for the divergence, there have actually been a lot of cherry-pick commits to fix problems that are in both branches.

As for file incompatibilities, there are only two so far, which can be seen at https://github.com/frejanordsiek/hdf5storage/issues?q=is%3Aissue+is%3Aclosed+label%3A%22breaks+file+compatability%22 . There will be some API compatibilities for those who want to implement marshallers themselves, but to just normal users, no real API incompatibilities other than dropped Python, NumPy, and h5py versions.
