### ISSUE TITLE
Roll a new release

### ISSUE THREAD

**Issue by mrdomino** [frejanordsiek/hdf5storage#16]
The changes merged in pull request #15 fix functionality for some of our use cases, so we're currently shipping code (specifically, [muse player](https://bitbucket.org/interaxon/museplayer)) with a forked HEAD of hdf5storage. I'd love to shoot that fork in the head and replace our build with a setup.py or something at some point, but in order to do so, I'd need to point at a released version of hdf5storage.

**Comment by frejanordsiek** [comment]
I will roll a new release to PyPi with this bug fixed tonight then. It will be version ``0.1.4``.

**Comment by frejanordsiek** [comment]
New release uploaded to PyPi: https://pypi.python.org/pypi/hdf5storage

**Comment by mrdomino** [comment]
Thanks!
