### ISSUE TITLE
hdf5storage doesn't work for savemat

### ISSUE THREAD

**Issue by achatte** [frejanordsiek/hdf5storage#17]
import scipy.io as sio
a_dict = {'field1': 0.5, 'field2': 'a string'}
sio.savemat('saved_struct.mat', {'a_dict': a_dict}) 
#----------------------------------------------------
from pydal import DAL, Field
db = DAL('sqlite://storage.db')
db.define_table('thing',Field('name'))
db.thing.insert(name='Chair')
a = db().db.thing.as_dict();
#a is a dict, you can print out
#Now if you do 
sio.savemat('saved_struct.mat', {'a': a})
#gives you a type error because 
Could not convert None (type <type 'NoneType'>) to array 

#Tried with hdf5storage
import hdf5storage 
from hdf5storage import savemat
hdf5storage.savemat('text.mat',a)

Get this error: Dictionaries with non-unicode keys are not supported: 'authorize'
Any work around?

**Comment by frejanordsiek** [comment]
If you are using Python 2.x, then the error is coming from the fact that the keys of ``a`` are of type ``str`` instead of ``unicode``. You need to convert the keys to ``unicode`` with a line like

``` python
dict([(k.decode(), v) for k, v in a.items()])
```

Now, if you are using Python 3.x, then this means that there is an error in the hdf5storage package that I need to fix.

Which Python version are you using?

**Comment by achatte** [comment]
U r very smart. Yes. I was using 2.7.6

**Comment by achatte** [comment]
I tried with decode like u said using python 2.7...it still didnt work

**Comment by frejanordsiek** [comment]
It does not modify ``a`` in place.

Did you do something like

``` python
b = dict([(k.decode(), v) for k, v in a.items()])
hdf5storage.savemat('text.mat', b)
```

or something else? I think I might be able to figure out a work around if you did do this.

**Comment by achatte** [comment]
U can almost read my mind! Yes, thats exactly what I did.

**Comment by frejanordsiek** [comment]
It is definitely a full on bug then. I will get digging.

**Comment by frejanordsiek** [comment]
OK, so I found out what was wrong. ``a`` has some dicts nested inside it that have non ``unicode`` keys. Your example will work if we add the following lines

``` python
def dict_keys_to_unicode(d):
    out = dict()
    for k, v in d.items():
        out[k.decode()] = v
    return out

b = dict_keys_to_unicode(a)
b[u'fields'] = [dict_keys_to_unicode(d) for d in b[u'fields']]
```

making the full example

``` python
from pydal import DAL, Field
db = DAL('sqlite://storage.db')
db.define_table('thing',Field('name'))
db.thing.insert(name='Chair')
a = db().db.thing.as_dict();

def dict_keys_to_unicode(d):
    out = dict()
    for k, v in d.items():
        out[k.decode()] = v
    return out

b = dict_keys_to_unicode(a)
b[u'fields'] = [dict_keys_to_unicode(d) for d in b[u'fields']]

import hdf5storage
from hdf5storage import savemat
hdf5storage.savemat('text.mat',a)
```

**Comment by achatte** [comment]
The last line save parameter should be a 'b' not an a. When I changed that.
It works. Awesome!

**Comment by frejanordsiek** [comment]
Typo in the example has been fixed.
