### ISSUE TITLE
Merge this project to scipy.io

### ISSUE THREAD

**Issue by dashesy** [frejanordsiek/hdf5storage#31]
Right now `scipy.io` cannot handle mat files after version 7.3 but `hdf5storage` provides a `loadmat` for them (it seems to be very slow but it works). 

I think I realized why it is so slow. MATLAB creates arrays of reference objects not only for UTF8 string cell arrays, but also for simple data types such as `double`. When these reference arrays are large, dereferencing them one by one in Python is slow. I think this can be handled in a C extension. MATLAB loads the file fast enough and `HDFView` Java application itself also loads it fast.

**Comment by frejanordsiek** [comment]
It is indeed all the reference arrays that causes problems for hdf5storage, which is written in pure python at the present time. I am hoping to convert some of the core functions over to Cython once I do a few more things with the API on the way Marshallers work. Some of the API changes will be needed to make the conversion to Cython easier. If after Cythonizing some of the functions where the performance is worst there are still performance problems, then it will be time to go to straight C (hopefully this won't be necessary).

On the topic of merging into scipy.io, I don't think it would work that well. For one, this package would need to be a lot more polished before it would be worth their time (this package's code is a total mess). Second, it adds h5py and the hdf5 libraries as a dependency and h5py also depends on numpy. Third, the support for all the non-numpy types is probably not something that would be in scope of scipy, though a stripped down version that only worked with numpy types might be a different story in that regard.
