### ISSUE TITLE
Test failures with Python 2 on Debian

### ISSUE THREAD

**Issue by ghisvail** [frejanordsiek/hdf5storage#47]
Hi Freja,

The Debian CI is reporting test failures for `hdf5storage` running against the latest version of Python 2 (2.7.12) available on Debian testing / unstable. The build log is available [here](https://ci.debian.net/data/packages/unstable/amd64/p/python-hdf5storage/20160907_225148.autopkgtest.log.gz).

If this issue is already fixed, please consider releasing a new stable version or point me to the relevant commit addressing the issue.

```
======================================================================
FAIL: test_write_readback.TestMatlabFormat.test_str_ascii_encoded_utf8
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/usr/lib/python2.7/dist-packages/nose/tools/nontrivial.py", line 67, in newfunc
    raise AssertionError(message)
AssertionError: test_str_ascii_encoded_utf8() did not raise NotImplementedError

======================================================================
FAIL: test_write_readback.TestPythonMatlabFormat.test_str_ascii_encoded_utf8
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/usr/lib/python2.7/dist-packages/nose/tools/nontrivial.py", line 67, in newfunc
    raise AssertionError(message)
AssertionError: test_str_ascii_encoded_utf8() did not raise NotImplementedError

----------------------------------------------------------------------
Ran 971 tests in 15.827s
```

Cheers,

**Comment by frejanordsiek** [comment]
Is this on the last release of the 0.1.x branch or is this on the latest version here on github? I ask because I did some overhauling the string testing in recent times due to a bug I found in the string testing (there is a recent closed issue on it), but I could have introduced a new problem when fixing it. Basically, were the failures on the code before or after the fix (of course, it could be another problem entirely)?

**Comment by ghisvail** [comment]
This is on the latest release available in PyPI.

**Comment by frejanordsiek** [comment]
OK, I ran into an issue that gives back the exact same result (could of course be another bug) and fixed it a little while ago (commit 0f67d66). Basically, my method of generating random strings to have non-ASCII characters has some probability of being pure ASCII. The fix causes the random string to be regenerated until it has at least one non-ASCII character in it.

Can you test if that commit fixes it.

I will see if I can roll out a bugfix release within a week.

**Comment by ghisvail** [comment]
> Can you test if that commit fixes it.

That's going to be difficult to test, since the failure frequency is low (2 out of the last 20]).

> I will see if I can roll out a bugfix release within a week.

That would be more sensible.

Thanks,
Ghis

**Comment by frejanordsiek** [comment]
Well, the fact you said that the failure rate is low (2 out of the last 20) tells me that it is almost for sure the same error then. That was about like I was getting.

I'm working on the NaN warning thing and will try to get the bugfix out.
