### ISSUE TITLE
conda-forge package

### ISSUE THREAD

**Issue by jakirkham** [frejanordsiek/hdf5storage#59]
Opening this mainly to raise awareness. Am working on a [`conda`]( https://conda.io/docs/ ) package of `hdf5storage` for inclusion in [`conda-forge`]( https://conda-forge.github.io/ ) with PR ( https://github.com/conda-forge/staged-recipes/pull/3140 ). This will allow installing `hdf5storage` with dependencies from `conda-forge`. Feel free to share feedback on that PR or the subsequent feedstock (once the PR is merged). Also if anyone has interest in being a maintainer, am more than happy to include others.

**Comment by jakirkham** [comment]
FYI here is the [`hdf5storage` feedstock]( https://github.com/conda-forge/hdf5storage-feedstock ). Packages for Mac, Linux, and Windows are now available.

**Comment by frejanordsiek** [comment]
Thank you for working on this.
