### ISSUE TITLE
Add optional compression for large Datasets

### ISSUE THREAD

**Issue by frejanordsiek** [frejanordsiek/hdf5storage#6]
Would allow major space savings. One issue will be choosing chunk size. The h5py package has a builtin autochunk size feature which might be good enough. For compatibility with other sofware, the Deflate (gzip) compression algorithm is best.

**Comment by wanglongqi** [comment]
+1

**Comment by frejanordsiek** [comment]
Thank you. I had originally added those for future use but hadn't gotten around to using them yet. Was going to for the 0.3 release, but I will speed it up for the 0.2 release which I am going to try to get out very soon. I am going to add a feature to it, which is a minimum variable size for compression so that very small variables don't get compressed since that might actually take up more space but big ones do get compressed, which will be the default.

**Comment by wanglongqi** [comment]
That is a very useful feature. I just implemented this code in a rush for converting the old .mat files to new  version. I think your design is more robust in general case. Looking forward to your implementation. Thanks for designing this wonderful package!

**Comment by frejanordsiek** [comment]
Commit [b63e61](https://github.com/frejanordsiek/hdf5storage/commit/b63e610bea6cc66eeaa350ca1a9f127f07cb6631) adds compression features. I also removed your pull request since the compression features replace it and are more comprehensive.

``hdf5storage.Options`` now has the following options to affect the compression and filters

``compress``
``copmress_size_threshold``
``compression_algorithm``
``gzip_compression_level``
``shuffle_filter``
``compressed_fletcher32_filter``
``uncompressed_fletcher32_filter``

**Comment by frejanordsiek** [comment]
The compression features are now heavily unit tested in addition to being hand tested. The test file is [https://github.com/frejanordsiek/hdf5storage/blob/master/tests/test_hdf5_filters.py](master/tests/test_hdf5_filters.py). The commits for the tests are

[https://github.com/frejanordsiek/hdf5storage/commit/4583a9c2a2275775194ba5251c965a0d0cee64c7](4583a9c)
[https://github.com/frejanordsiek/hdf5storage/commit/ec9a6cec26b64e140cb66c3d02149f8439e2aae1](ec9a6ce)
[https://github.com/frejanordsiek/hdf5storage/commit/6ac17d3b289cdf5f1fbf9ed2cf153af13bb614af](6ac17d3)
[https://github.com/frejanordsiek/hdf5storage/commit/ed278b981fb09c57e4c7e7b2040e2b4d4241702f](ed278b9)
[https://github.com/frejanordsiek/hdf5storage/commit/bdd216c3b71e9ff22ccd87bf196053ba09f7f166](bdd216c)

In addition, the version 0.1.6 can read compressed data. The test file is [https://github.com/frejanordsiek/hdf5storage/blob/0.1.x/tests/test_hdf5_filters.py](0.1.x/tests/test_hdf5_filters.py). The commits for the tests are

[https://github.com/frejanordsiek/hdf5storage/commit/8b6e6e38653aeda3d1bf6f70c49da66277838b76](8b6e6e3)
[https://github.com/frejanordsiek/hdf5storage/commit/e49b3ef8221cb1c380abb7910ff6fa818e8b4d9e](e49b3ef8)
[https://github.com/frejanordsiek/hdf5storage/commit/cd7f908238c96499167b3cf9837d0d7478e14ee8](cd7f908)
[https://github.com/frejanordsiek/hdf5storage/commit/c19a43017bd2f0b57453973aed5d0572e895c7f1](c19a430)

I am going to try to roll out the 0.2 release that adds compression support along with a few other features I already added (longs/ints too big for int64 and better non-ascii character support). I need to add more documentation for the features.

I am not going to roll out 0.1.7 just to add the unit test code (only real change). Going to wait till some actual bugs are found on that one.

**Comment by frejanordsiek** [comment]
Added documentation pages. The commits are

[e8b33a0](https://github.com/frejanordsiek/hdf5storage/commit/e8b33a0bf1b4c0897fc7ae7491143ed2000d4325)
[95bcf29](https://github.com/frejanordsiek/hdf5storage/commit/95bcf291dbd280c03e3693d0ff2a488e792db7e7)

The 0.1.7 version was released, followed by the 0.1.8 version. They don't support compression when writing, but they can read it and they do take the compression options without throwing an error (though they do ignore them).

**Comment by frejanordsiek** [comment]
Version 0.1.9 has been released. It supports using compression when writing data. Formatted documentation is at https://pythonhosted.org/hdf5storage/compression.html
