### ISSUE TITLE
support for python 3.6 ?

### ISSUE THREAD

**Issue by pashute** [frejanordsiek/hdf5storage#67]
Are there known problems?  

Does it run in 3.6?  

Is there any equivalent?

**Comment by frejanordsiek** [comment]
There are no problems that I know of for the master branch. Don't know about 0.1.x branch. I don't think there should be any problems on 3.6.

See https://travis-ci.org/frejanordsiek/hdf5storage for the master branch.

For 0.1.x, the most recent tests are at https://travis-ci.org/frejanordsiek/hdf5storage/builds/159604803 . It should be noted that python-nightly at the time was the developmental version of 3.6 before release. At least at that time, there were no issues.

**Comment by pashute** [comment]
Thank you. That completely answers my question.
