### ISSUE TITLE
Error when reading -v7.3 matfile written by hdf5storage.savemat with matio library functions

### ISSUE THREAD

**Issue by EBenkler** [frejanordsiek/hdf5storage#69]
I try to load a -v7.3 matfile saved from python by hdf5storage.savemat in scilab 6.0 using scilab function loadmatfile.sci (uses matio library functions) and get the error :
Do not know how to read a variable of class 0.

Matlab correctly loads the variables into its workspace.

This is how I save the mat file in python (all variables are numpy arrays or matrices):
```python
mdict = {'t': t, 'frequencies': frequencies, 'resync_ind': resync_ind,
                 'pps_ind': pps_ind, 't_frac': t_frac, 'fdi_data': fdi_data, 'corr_ind': corr_ind}
hdf5storage.savemat("180220_FXE_data.mat", mdict)
```

and this is a small scilab script checking names, types and classes of the variables saved in the matfile:
```scilab
fd = matfile_open("180220_FXE_data.mat");
[name, classes, types]=matfile_listvar(fd);
matfile_close(fd);
for i=1:size(name,"*") do
    disp("The variable " + name(i) + " has type " + string(types(i)) + " and class " + string(classes(i)))
end
```
which generates the following output:
 The variable corr_ind has type 0 and class 0
 The variable fdi_data has type 0 and class 0
 The variable frequencies has type 0 and class 0
 The variable pps_ind has type 0 and class 0
 The variable resync_ind has type 0 and class 0
 The variable t has type 0 and class 0
 The variable t_frac has type 0 and class 0

Am I doing something stupid or is this a bug?

**Comment by frejanordsiek** [comment]
Do you have the matfile itself, and would it be OK if I took a look? Or a similar synthetic one that produces the same sort of error but would be OK to look at? I can take a look at it in hdfview and maybe I can figure out which end (hdf5storage or scilab) is doing something wrong, or both.
