### ISSUE TITLE
Memory not being freed up after calls to loadmat

### ISSUE THREAD

**Issue by luriol** [frejanordsiek/hdf5storage#76]
I am using hdf5storage.loadmat to read through a large number of matlab files in a directory.  The total memory used by python seems to continually increase until I run out of memory in my system.  Here is the code below along with the output.  How do I prevent the memory usage from continuously growing?

from os import listdir
from hdf5storage import loadmat

def memory():
    import os
    from wmi import WMI
    w = WMI('.')
    result = w.query("SELECT WorkingSet FROM Win32_PerfRawData_PerfProc_Process WHERE IDProcess=%d" % os.getpid())
    return int(result[0].WorkingSet)/1024/1024

mydir='d:/Nov_2018_Crystallin_Run/file1/Analysis_12_20/B120/'

for datafile in listdir(mydir):
    fname=mydir+datafile
    fout =loadmat(fname)
    print('memory used {0:7.0f}M'.format(memory()))

Program Output 
memory used     280M
memory used     291M
memory used     303M
memory used     313M
memory used     323M
memory used     334M
memory used     345M
memory used     355M

**Comment by SKb10** [comment]
Maybe you can try subprocess, like:
```
import subprocess
args = [f'{python_bin}', 'script.py', f'{p1}', f'{p2}']
subprocess.run(args)
```
then you can limit the memory usage into the script.
https://docs.python.org/3/library/subprocess.html

**Comment by luriol** [comment]
Thanks for the suggestion.  I was able to get a workaround using the multiprocessing library see below.  

from multiprocessing import Process, Queue
from hdf5storage import loadmat,savemat
from os import listdir

def readmatfile(q,fname):
    matres = loadmat(fname)
    G2 = matres['viewresultinfo']['result']['G2'][0][0][0][0]
    q.put(G2)

mydir='d:/Nov_2018_Crystallin_Run/file1/Analysis_12_20/B120/'

if __name__ == '__main__':
    for datafile in listdir(mydir):
        q = Queue()
        fname= mydir+datafile
        p = Process(target=readmatfile, args=(q,fname))
        p.start()
        fout=q.get()
        print(fname)
        try:
            G2+=fout
        except:
            G2=fout[0]
        p.join()

**Comment by frejanordsiek** [comment]
Not sure if you are still having the problem or not. What are the types of the data you are reading (structures, cell arrays, large n-d arrays of numbers, etc.)? Depending on the data types, I might have a few ideas. For example, reading in any sort of cyclic data structure (imagine two cell arrays that each refer to each other) will cause all RAM to be used up no matter how much RAM the system has. hdf5storage does not check for such cycles yet. Cell arrays take up a lot of memory and take quite a while to read as well.

**Comment by luriol** [comment]
I am still having this problem.  The workaround above solves it, but is not particularly elegant, and slows things down.  The data I am reading is from a matlab file.  It is not a cell array but a structure.   Using loadmat, I address it using matres['viewresultinfo']['result']['G2'][0][0][0][0].  In native matlab the structure is viewresultinfo.result.G2.  The last layer is a two dimensional array.

**Comment by luriol** [comment]
I am still having this problem. The workaround above solves it, but is not particularly elegant, and slows things down. The data I am reading is from a matlab file. It is not a cell array but a structure. Using loadmat, I address it using matres['viewresultinfo']['result']['G2'][0][0][0][0]. In native matlab the structure is viewresultinfo.result.G2. The last layer is a two dimensional array.
