### ISSUE TITLE
Append data to avoid loading on memory

### ISSUE THREAD

**Issue by vsudhir82** [frejanordsiek/hdf5storage#77]
Hi 

I have application where I am trying to merge several .mat files (V 7.3) into single .mat file. 
Also the application can plot any .mat (7.3) in graphs for some analysis. 
The input .mat files are read using H5PY dict with each key having large Matrices or 2D array (some data Vs Time stamps). 

Issue 1 Write:
I was reading input files for each key & appending the data on memory. And once reading is complete HDF5 savemat( ).  The problem I am facing is numpy array crashes with memory error after appending / concatenating certain size (if input files size or number of files are more).
I tried memory map Numpy but then to save it I have to load at some point. Which again crashes cause the data size is large. 
So was wondering if there is better way to append data at end of existing dict in .mat file using HDF5 without loading much on memory. ?? write( ) or writes ( ) overwrites the data if I am correct ? 

Issue 2 Read : 
Similar to above mentioned issue is there dict data inside .mat file has  large matrix then is it possible to read single row or part of data in 1D array without loading entire data ?

I was partly successful in merging data using H5PY create_dataset & then resizing the data set before appending the data. But then have same problem using Numpy reading large data, 

Input files can be anything fro 50mb To 900mb each. 

Environment:
Python 3.7 64b
matplotlib
numpy 1.16 (don't remember last minor number)
HDF5 Storage

**Comment by frejanordsiek** [comment]
You have probably long found a workaround for this, but answering here just in case. Only thing I can think of is to read and write variables one at a time, which is a less than satisfactory solution. Reading big structured datasets can be memory intensive. hdf5storage unfortunately does not make its arrays in such a way that any of their dimensions can be resized, so it is hard to append to them manually one array at a time on disk.

**Comment by vsudhir82** [comment]
Thank you Freja !!
I found workaround by writing individual data arrays & further breaking
down Raw signals wave forms index wise. This helped me log upto 15 hours of
continuous data which was sufficient in my case .
Thanks again , Stay safe & TC.
