### ISSUE TITLE
Compatability with pathlib

### ISSUE THREAD

**Issue by csheaff** [frejanordsiek/hdf5storage#78]
Using hdf5storage with pathlib paths results in the following error:

> AttributeError: 'PosixPath' object has no attribute 'endswith'

**Comment by frejanordsiek** [comment]
pathlib is not supported yet. Right now, all paths must be str. But this is a feature that should definitely be added.

**Comment by frejanordsiek** [comment]
Added support to the master branch in commit 13526865f5de2cd043c166db9516ead252086b52. Testing of it was added to the existing write_readback tests in commit 14db7dc230db27fd81352d4d639af25b87eea491.
