### ISSUE TITLE
loadmat: Give a sane error if a non-existent variable is requested

### ISSUE THREAD

**Issue by randallpittman** [frejanordsiek/hdf5storage#79]
## Problem

hdf5storage should clearly tell the user when a requested variable is not present in a v7.3 MAT file with an error that can be handled in a `try...except` block. At present, hdf5storage just thinks it can't read the file and tries to open it with `scipy.io.loadmat`.

EDIT: It would be nice to also have a `skip_if_missing` feature. I'm loading a bunch of MAT files (some pre 7.3, some 7.3), some with fields that were added later.

EDIT2: It should be noted that for pre-7.3 files, `scipy.io.loadmat` silently ignores non-existent requested variables. Would be nice to have this behavior for consistency.

## Example

Say I have v7.3 MAT file `mydata.mat`, and this file does _not_ have the variable  `missing_var` in it.

If I run
```python
mat_data = hdf5storage.loadmat("mydata.mat", variable_names=["missing_var"])
```
Then I get a long traceback ultimately ending in `NotImplementedError: Please use HDF reader for matlab v7.3 files`. If I look up the traceback I eventually find 
```
CantReadError: Could not find /missing_var

During handling of the above exception, another exception occurred:

NotImplementedError                       Traceback (most recent call last)
```
But I can't catch `CantReadError` in a `try...except` block.

Since `CantReadError` is a subclass of `OSError`, hdf5storage thinks maybe it's a pre-7.3 file, and then `scipy.io.loadmat` says, "Hey, this is a 7.3 file, you should be using h5py or something".

**Comment by frejanordsiek** [comment]
Fixed in commit db58316 for the master branch and commit 599503a for the 0.1.x branch. It now just skips missing variables.
