### ISSUE TITLE
(Incredibly) Slow loadmat

### ISSUE THREAD

**Issue by jungerm2** [frejanordsiek/hdf5storage#86]
I'm struggling to understand why this is happening:

![image](https://user-images.githubusercontent.com/17375657/79908299-fee08600-83e8-11ea-84ce-564ce06552d9.png)

I'm using [this](http://horatio.cs.nyu.edu/mit/silberman/nyu_depth_v2/nyu_depth_v2_labeled.mat) file, and the latest version of both libraries.

Thanks!

**Comment by danielhrisca** [comment]
@jungerm2 reading a 2.8GB file in 30us ? I think the h5py code just opens the file, without actually reading anything from it

**Comment by jungerm2** [comment]
That's fair, but why doesn't loadmat perform lazy loading like h5py does?
(Sorry for the late reply...)

**Comment by frejanordsiek** [comment]
At the present time, hdf5storage.loadmat opens the file and reads everything in the root Group as a variable and returns them, as opposed to giving you a file handle that you can then load variables from. This is just like scipy.io.loadmat.

Note, in version 1.0, I do plan on making a class that will allow variables to be read and written after loading, so such a feature will eventually come. But the existing functions will continue to behave as they already do for backwards compatibility.

**Comment by jungerm2** [comment]
Oh great! It's nice to see that this package is actively maintained. Thanks for the update.

**Comment by frejanordsiek** [comment]
It isn't very maintained though. I am hoping to slowly get some issues sorted out and make a 1.0 release, but this process has been years in the making. After that, it will just be bugfixes probably.

**Comment by frejanordsiek** [comment]
Just added the File class in the base module in commit fd9bb548b2d79cf0e3d71dd1e952d0a39f0ccabc. One can open a file with it and do multiple read and write calls with it. The read, reads, write, and writes functions are now just wrappers around it and methods having the same names.
